# Generated by Django 4.0 on 2023-09-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='imagen',
            field=models.ImageField(blank=True, default='cine/cine_default.jpg', null=True, upload_to='cine'),
        ),
    ]
